"""Add suppliers, products and stock movements.

Revision ID: 20260718_05
Revises: 20260718_04
Create Date: 2026-07-18
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "20260718_05"
down_revision: str | None = "20260718_04"
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def timestamp_columns() -> list[sa.Column]:
    return [
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text(
                "CURRENT_TIMESTAMP"
            ),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text(
                "CURRENT_TIMESTAMP"
            ),
            nullable=False,
        ),
    ]


def upgrade() -> None:
    op.create_table(
        "suppliers",
        sa.Column(
            "id",
            sa.Uuid(),
            nullable=False,
        ),
        sa.Column(
            "legal_name",
            sa.String(length=160),
            nullable=False,
        ),
        sa.Column(
            "trade_name",
            sa.String(length=160),
            nullable=True,
        ),
        sa.Column(
            "document",
            sa.String(length=32),
            nullable=True,
        ),
        sa.Column(
            "contact_name",
            sa.String(length=120),
            nullable=True,
        ),
        sa.Column(
            "email",
            sa.String(length=255),
            nullable=True,
        ),
        sa.Column(
            "phone",
            sa.String(length=32),
            nullable=True,
        ),
        sa.Column(
            "address",
            sa.Text(),
            nullable=True,
        ),
        sa.Column(
            "notes",
            sa.Text(),
            nullable=True,
        ),
        sa.Column(
            "active",
            sa.Boolean(),
            server_default=sa.text("true"),
            nullable=False,
        ),
        *timestamp_columns(),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_index(
        "ix_suppliers_trade_name",
        "suppliers",
        ["trade_name"],
        unique=False,
    )
    op.create_index(
        "ix_suppliers_document",
        "suppliers",
        ["document"],
        unique=True,
    )
    op.create_index(
        "ix_suppliers_email",
        "suppliers",
        ["email"],
        unique=False,
    )
    op.create_index(
        "ix_suppliers_phone",
        "suppliers",
        ["phone"],
        unique=False,
    )
    op.create_index(
        "ix_suppliers_active",
        "suppliers",
        ["active"],
        unique=False,
    )

    op.create_table(
        "products",
        sa.Column(
            "id",
            sa.Uuid(),
            nullable=False,
        ),
        sa.Column(
            "supplier_id",
            sa.Uuid(),
            nullable=True,
        ),
        sa.Column(
            "name",
            sa.String(length=160),
            nullable=False,
        ),
        sa.Column(
            "sku",
            sa.String(length=80),
            nullable=False,
        ),
        sa.Column(
            "barcode",
            sa.String(length=80),
            nullable=True,
        ),
        sa.Column(
            "description",
            sa.Text(),
            nullable=True,
        ),
        sa.Column(
            "unit_label",
            sa.String(length=24),
            server_default=sa.text("'un'"),
            nullable=False,
        ),
        sa.Column(
            "cost_cents",
            sa.Integer(),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "sale_price_cents",
            sa.Integer(),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "stock_quantity",
            sa.Integer(),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "minimum_stock",
            sa.Integer(),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "active",
            sa.Boolean(),
            server_default=sa.text("true"),
            nullable=False,
        ),
        *timestamp_columns(),
        sa.CheckConstraint(
            "cost_cents >= 0",
            name="ck_products_cost_non_negative",
        ),
        sa.CheckConstraint(
            "sale_price_cents >= 0",
            name=(
                "ck_products_sale_price_"
                "non_negative"
            ),
        ),
        sa.CheckConstraint(
            "stock_quantity >= 0",
            name="ck_products_stock_non_negative",
        ),
        sa.CheckConstraint(
            "minimum_stock >= 0",
            name=(
                "ck_products_minimum_stock_"
                "non_negative"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["supplier_id"],
            ["suppliers.id"],
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_index(
        "ix_products_supplier_id",
        "products",
        ["supplier_id"],
        unique=False,
    )
    op.create_index(
        "ix_products_name",
        "products",
        ["name"],
        unique=False,
    )
    op.create_index(
        "ix_products_sku",
        "products",
        ["sku"],
        unique=True,
    )
    op.create_index(
        "ix_products_barcode",
        "products",
        ["barcode"],
        unique=True,
    )
    op.create_index(
        "ix_products_stock_quantity",
        "products",
        ["stock_quantity"],
        unique=False,
    )
    op.create_index(
        "ix_products_minimum_stock",
        "products",
        ["minimum_stock"],
        unique=False,
    )
    op.create_index(
        "ix_products_active",
        "products",
        ["active"],
        unique=False,
    )

    op.create_table(
        "stock_movements",
        sa.Column(
            "id",
            sa.Uuid(),
            nullable=False,
        ),
        sa.Column(
            "product_id",
            sa.Uuid(),
            nullable=False,
        ),
        sa.Column(
            "supplier_id",
            sa.Uuid(),
            nullable=True,
        ),
        sa.Column(
            "user_id",
            sa.Uuid(),
            nullable=True,
        ),
        sa.Column(
            "movement_type",
            sa.String(length=24),
            nullable=False,
        ),
        sa.Column(
            "quantity_delta",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "stock_before",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "stock_after",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "unit_cost_cents",
            sa.Integer(),
            nullable=True,
        ),
        sa.Column(
            "reason",
            sa.String(length=255),
            nullable=False,
        ),
        sa.Column(
            "reference",
            sa.String(length=120),
            nullable=True,
        ),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text(
                "CURRENT_TIMESTAMP"
            ),
            nullable=False,
        ),
        *timestamp_columns(),
        sa.CheckConstraint(
            "quantity_delta <> 0",
            name=(
                "ck_stock_movements_"
                "quantity_non_zero"
            ),
        ),
        sa.CheckConstraint(
            "stock_before >= 0",
            name=(
                "ck_stock_movements_"
                "before_non_negative"
            ),
        ),
        sa.CheckConstraint(
            "stock_after >= 0",
            name=(
                "ck_stock_movements_"
                "after_non_negative"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["supplier_id"],
            ["suppliers.id"],
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_index(
        "ix_stock_movements_product_id",
        "stock_movements",
        ["product_id"],
        unique=False,
    )
    op.create_index(
        "ix_stock_movements_supplier_id",
        "stock_movements",
        ["supplier_id"],
        unique=False,
    )
    op.create_index(
        "ix_stock_movements_user_id",
        "stock_movements",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        "ix_stock_movements_movement_type",
        "stock_movements",
        ["movement_type"],
        unique=False,
    )
    op.create_index(
        "ix_stock_movements_reference",
        "stock_movements",
        ["reference"],
        unique=False,
    )
    op.create_index(
        "ix_stock_movements_occurred_at",
        "stock_movements",
        ["occurred_at"],
        unique=False,
    )


def downgrade() -> None:
    op.drop_index(
        "ix_stock_movements_occurred_at",
        table_name="stock_movements",
    )
    op.drop_index(
        "ix_stock_movements_reference",
        table_name="stock_movements",
    )
    op.drop_index(
        "ix_stock_movements_movement_type",
        table_name="stock_movements",
    )
    op.drop_index(
        "ix_stock_movements_user_id",
        table_name="stock_movements",
    )
    op.drop_index(
        "ix_stock_movements_supplier_id",
        table_name="stock_movements",
    )
    op.drop_index(
        "ix_stock_movements_product_id",
        table_name="stock_movements",
    )
    op.drop_table("stock_movements")

    op.drop_index(
        "ix_products_active",
        table_name="products",
    )
    op.drop_index(
        "ix_products_minimum_stock",
        table_name="products",
    )
    op.drop_index(
        "ix_products_stock_quantity",
        table_name="products",
    )
    op.drop_index(
        "ix_products_barcode",
        table_name="products",
    )
    op.drop_index(
        "ix_products_sku",
        table_name="products",
    )
    op.drop_index(
        "ix_products_name",
        table_name="products",
    )
    op.drop_index(
        "ix_products_supplier_id",
        table_name="products",
    )
    op.drop_table("products")

    op.drop_index(
        "ix_suppliers_active",
        table_name="suppliers",
    )
    op.drop_index(
        "ix_suppliers_phone",
        table_name="suppliers",
    )
    op.drop_index(
        "ix_suppliers_email",
        table_name="suppliers",
    )
    op.drop_index(
        "ix_suppliers_document",
        table_name="suppliers",
    )
    op.drop_index(
        "ix_suppliers_trade_name",
        table_name="suppliers",
    )
    op.drop_table("suppliers")
